channels:
  - conda-forge
dependencies:
  - python
  - scikit-learn
  - pandas
  - scipy
  - imbalanced-learn
  - plotly
  - python-kaleido
  - pip
  - pyyaml
  - h5py
  - pip:
    - git+https://${GITHUB_TOKEN}@github.com/brain-tools/esce.git@dev
